"""empty message

Revision ID: 24f9f0be0ca0
Revises: 9ea739407204
Create Date: 2021-04-04 20:10:46.889498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24f9f0be0ca0'
down_revision = '9ea739407204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_genre_table')
    op.drop_table('Genre')
    op.drop_table('artist_genre_table')
    op.add_column('Artist', sa.Column('genres', postgresql.ARRAY(sa.String(length=120)), nullable=True))
    op.alter_column('Show', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('Venue', sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.alter_column('Show', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('Artist', 'genres')
    op.create_table('artist_genre_table',
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='artist_genre_table_artist_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], name='artist_genre_table_genre_id_fkey'),
    sa.PrimaryKeyConstraint('genre_id', 'artist_id', name='artist_genre_table_pkey')
    )
    op.create_table('Genre',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Genre_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Genre_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('venue_genre_table',
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], name='venue_genre_table_genre_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='venue_genre_table_venue_id_fkey'),
    sa.PrimaryKeyConstraint('genre_id', 'venue_id', name='venue_genre_table_pkey')
    )
    # ### end Alembic commands ###
